---
version: 1
disable_existing_loggers: False
formatters:
  simple:
    format: "%(asctime)s %(name)s:%(funcName)s:%(lineno)d %(threadName)s %(levelname)-7s %(message)s"
  json:
    format: "%(asctime)s %(name)s:%(funcName)s:%(lineno)d %(threadName)s %(levelname)s %(message)s"
    class: pythonjsonlogger.jsonlogger.JsonFormatter

#  asctime
#  created
#  filename
#  funcName
#  levelname
#  levelno
#  lineno
#  module
#  msecs
#  message
#  name
#  pathname
#  process
#  processName
#  relativeCreated
#  thread
#  threadName

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: json
    filename: info.log
    maxBytes: 1048576 # 1 MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: json
    filename: errors.log
    maxBytes: 1048576 # 1 MB
    backupCount: 20
    encoding: utf8

loggers:
  classinvoices:
    level: DEBUG
    handlers: [console, info_file_handler, error_file_handler]
    propagate: no

root:
  level: INFO
  handlers: [console, info_file_handler, error_file_handler]
